### ISSUE TITLE
html entity in replace

### ISSUE THREAD

**Issue by julientaq** [edemaine/markdown-it-replacements#1]
Hi there,
thanks for this great tool.

i’m trying to add HTML entities (trying to make a french typographer plugin, for which i’d like to have html element around (`span` basically) but everything is escaped, like this:
 
```
mir.replacements.push({
  name: "thoushand",
  re: /(\d)([ | ])(\d)/gi,
  sub: '$1\<span class=\"th\"\>\u2009\<\/span\>$2',
  default: true,
});
```

get transformed into

```
this is fine 199<span class="th"> </span> 00
```

Is there a simple way to avoid this?

Thanks!

**Comment by julientaq** [comment]
Hoy,

found a fork of your work here with html replacement

https://github.com/gabipetrovay/markdown-it-replace-it

don’t know if you were aware of that one. 
Thanks!

**Comment by edemaine** [comment]
Ah, interesting, thanks for the pointer!
